server:
  port: 8080

spring:
  application:
    name: pm-ingest

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
